#!/usr/bin/env bash
# Writes a gitignored Expo environment file for linked-worktree debug builds.
# The install identity is keyed to the worktree directory, so it remains stable
# across branch switches. apps/mobile/app.config.ts validates and consumes the
# values. The main checkout and all release builds retain production identity.
set -euo pipefail

# An inherited GIT_DIR pointing elsewhere must not misdetect the worktree.
unset GIT_DIR GIT_WORK_TREE

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
env_file="$repo_root/apps/mobile/.env.worktree.local"

# Worktree detection: in the main working tree --git-dir and --git-common-dir
# are identical; in any linked worktree they differ (same check as
# scripts/instance-env.sh).
in_worktree=0
if git -C "$repo_root" rev-parse --is-inside-work-tree &>/dev/null; then
    git_dir=$(git -C "$repo_root" rev-parse --git-dir)
    git_common_dir=$(git -C "$repo_root" rev-parse --git-common-dir 2>/dev/null)
    if [[ -n "$git_common_dir" && "$git_dir" != "$git_common_dir" ]]; then
        in_worktree=1
    fi
fi

if [[ "$in_worktree" != "1" ]]; then
    rm -f "$env_file"
    exit 0
fi

# Install identity comes from the worktree directory name: stable across
# branch switches, so one worktree keeps one installed app (and its login
# state) no matter how many branches it visits.
worktree_name="$(basename "$repo_root")"

# Display label is context only: the branch name, or a short SHA when the
# worktree is detached. Sanitized to [A-Za-z0-9._-] so no valid Git ref can
# break Android string resources or xcconfig values.
branch=$(git -C "$repo_root" rev-parse --abbrev-ref HEAD)
if [[ "$branch" == "HEAD" ]]; then
    label_raw=$(git -C "$repo_root" rev-parse --short HEAD)
else
    label_raw="${branch##*/}"
fi
label=$(printf '%s' "$label_raw" | sed -e 's/[^A-Za-z0-9._-]/-/g' -e 's/--*/-/g' -e 's/^-//' -e 's/-$//')
[[ -n "$label" ]] || label="worktree"

# iOS bundle-identifier slug: lowercase, non-alphanumerics collapsed to
# hyphens (hyphens are valid in bundle identifiers).
ios_slug=$(printf '%s' "$worktree_name" | tr '[:upper:]' '[:lower:]' | sed -e 's/[^a-z0-9]/-/g' -e 's/--*/-/g' -e 's/^-//' -e 's/-$//')
[[ -n "$ios_slug" ]] || ios_slug="worktree"

# Android applicationId segments must match [a-z][a-z0-9_]*: swap hyphens for
# underscores and prefix a letter when the slug starts with a digit.
android_slug="${ios_slug//-/_}"
case "$android_slug" in
    [0-9]*) android_slug="w_$android_slug" ;;
esac

ios_bundle_id="com.buzz.buzzMobile.${ios_slug}"
android_package="xyz.block.buzz.mobile.${android_slug}"

cat > "$env_file" <<ENV
# Generated by scripts/mobile-worktree-overrides.sh — gitignored, do not edit.
BUZZ_MOBILE_APP_NAME=Buzz-${label}
BUZZ_MOBILE_IOS_BUNDLE_IDENTIFIER=${ios_bundle_id}
BUZZ_MOBILE_ANDROID_PACKAGE=${android_package}
ENV

echo "📱 Worktree ${worktree_name}: label \"${label}\" (iOS ${ios_bundle_id}, Android ${android_package})"
