import path from "node:path";
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { tanstackRouter } from "@tanstack/router-plugin/vite";

// @ts-expect-error process is a Node.js global
const host = process.env.BUZZ_DESKTOP_DEV_HOST;

// https://vite.dev/config/
export default defineConfig(async () => ({
  plugins: [
    tanstackRouter({
      target: "react",
      routesDirectory: "./src/app/routes",
      generatedRouteTree: "./src/app/routeTree.gen.ts",
      virtualRouteConfig: "./src/app/routes.ts",
      quoteStyle: "double",
      semicolons: true,
      routeTreeFileHeader: [
        "// biome-ignore-all lint: generated by TanStack Router",
      ],
    }),
    react(),
  ],
  resolve: {
    alias: {
      "@": "/src",
      "@features-manifest": path.resolve(__dirname, "../preview-features.json"),
    },
  },

  // Keep local desktop development deterministic and compatible with remote
  // HMR when BUZZ_DESKTOP_DEV_HOST is explicitly configured.
  clearScreen: false,
  server: {
    port: parseInt(process.env.VITE_PORT || "1420", 10),
    strictPort: true,
    host: host || false,
    hmr: host
      ? {
          protocol: "ws",
          host,
          port: parseInt(process.env.VITE_HMR_PORT || "1421", 10),
        }
      : undefined,
  },
}));
